### ISSUE TITLE
Videos don't launch

### ISSUE THREAD

**Issue by mattstvmedia** [stantanasi/sflix#8] opened 2022-11-27 21:23 UTC
Shows error 1e000065

**Comment by stantanasi** [comment] 2022-11-28 09:21
Already told you, the exception `error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT` does not depend on my code. **There's nothing I can do to solve this issue.** Due to the video host changing encryption methods extremely often, the videos might not work.

Duplicate of #5

**Closed by stantanasi** 2022-11-28 09:21 UTC

**Comment by stantanasi** [comment] 2022-11-28 09:42
It is now possible to choose between two providers, on the brand new [release v1.2.0](https://github.com/stantanasi/sflix/releases/tag/v1.2.0). If the first provider does not work, you can try the second one.

`SFlix` is the provider used on previous versions, and `AllMoviesForYou` is a new provider I chose to implement.

![Choose a provider](https://user-images.githubusercontent.com/46174829/204240561-a5de7c34-256d-4e0a-a48d-45d7dbe02291.png)

**Comment by stantanasi** [comment] 2022-12-06 11:51
**Improve on [Release 1.2.1](https://github.com/stantanasi/sflix/releases/latest)**
